### PR TITLE
Improve portability of shell scripts and make rules

### PR DESCRIPTION
**Pull request by mtmiller**
Eliminate bashisms in shell scripts and options that are GNU extensions.

### CODE REVIEW

**Comment by cbm755** [comment]
Thanks!  The `make` stuff is most important. 

The other scripts were never really intended to be platform independent---just to automate my workflow.  `s|/bin/sh/|/bin/bash|` might've been easier... ;-)  

Have you tested?  I suppose I can just merge and fix up if necessary when I do the next release.

**Comment by mtmiller** [comment]
Btw, this need comes out of the `make_release_packages.sh` script failing horribly for me with `/bin/sh` set to `/bin/dash` on my system (as on most Debian and Ubuntu systems).

I tested both scripts on `master` with bash and compared the output to this branch tested with both the `bash` and `dash` shells and I get identical output from all runs.

**Comment by cbm755** [comment]
very thorough!  I shall personally try to be more careful and use `/bin/bash` by default.

**Comment by mtmiller** [comment]
I actually prefer `/bin/sh`, keeps me honest, but the choice is yours :) Thanks!

**Pull request merged**
