### PR TITLE
Minor changes to diff docs and tests

### PR DESCRIPTION
**Pull request by cbm755**
@latot, please review

### CODE REVIEW

**Comment by latot** [comment]
are you sure you want merge this into my master branch?

**Comment by latot** [comment]
my bad xD

**Comment by latot** [comment]
I think its fine, can i open a issue for this?, at least while we can check how now works SMT.

**Comment by cbm755** [comment]
Ok, thanks.  I'll merge for now as this makes no code changes.

Sure, file a bug.  Someday, we'd like to remove the "feature".

**Comment by cbm755** [comment]
travis failures are just the usual timeout, so merging.

**Pull request merged**
