### PR TITLE
Porting chebyshev functions to binop_helper

### LINKED ISSUE #387: port cheyshevU and T to binop_helper
currently `chebyshevU([sym(1) 2 3], x)` probably doesn't work.

Search for other functions that use `binop_helper` to see how to do this.

### PR DESCRIPTION
**Pull request by genuinelucifer**
Fixes #387

### CODE REVIEW

**Comment by genuinelucifer** [comment]
@cbm755 Sorry for the new PR.
I deleted the older branch and created a new branch with the same name. But the old PR didn't get updated.
.
This PR contains all the changes that you commented for. And it passes all the tests. Please review.

**Comment by cbm755** [comment]
Excellent!

**Comment by genuinelucifer** [comment]
@cbm755 Could you please help me select a slightly more dificult issue to tackle. I saw the issues list but except Pytave one, I could not decide which to start. And the pytave one seems pretty much complete...

**Comment by genuinelucifer** [comment]
@cbm755 I have submitted my draft for the GSoC proposal for 2-3 days now. It would be really helpful if you could please review it and provide some feedback.

**Comment by cbm755** [comment]
Re: GSoC.  I can try to review but where is it?  I didn't see anything on the octave maintainers list...  Maybe I missed it?

**Comment by genuinelucifer** [comment]
Not on the list.
I submitted it to google on gsoc site.
It says that it will be visible to all the members of the organization..
.
I could send it to you if you give me your email id.

**Comment by cbm755** [comment]
re: tasks, maybe #376 would be useful?

**Comment by cbm755** [comment]
> I could send it to you if you give me your email id.

email id?  My google login is "cbm755" (although I don't use it much).

**Comment by genuinelucifer** [comment]
I shared the proposal with you on your gmail ID. Also, I will start looking into the issue you suggested :)

**Pull request merged**
