### PR TITLE
move iscell check above error reporting

### PR DESCRIPTION
**Pull request by cbm755**
Also, inform the user that she might have been supposed to return
a tuple.

### CODE REVIEW

**Comment by cbm755** [comment]
@latot can you review this?

**Comment by latot** [comment]
mm, i only can say 2 things, in my experience only are two instances when this happens, first, we forget tuple in return, (here good), the other, broken octsympy/octave, would be great can do something here.

**Comment by cbm755** [comment]
ok, I added more to the error message.

**Comment by latot** [comment]
i was thinking, if we enable the normal return of python?
```
  if (~iscell(A))
    A={A};
  end
```
the normal return don't is an error... so i think can help.

**Comment by cbm755** [comment]
Good point, I filed another bug.

These blocks are still in the wrong order so I will merge this for now.

**Comment by cbm755** [comment]
(tests didn't pass, will try again after merge)

**Comment by latot** [comment]
mm, here always fails 3 tests, dsolve 2 tests and 1 test in orth.
using octave-4.0.0(no hg) and sympy git version

**Comment by cbm755** [comment]
yeah dsolve is pretty $%^ked up in SymPy, haven't had to time/motivation to fix it.

But I should fix up that test so it doesn't fail on 0.7.7-dev.

As you've surely noticed, I mostly want the tests to pass on Travis CI...

**Pull request merged**
