### PR TITLE
[maint] Add git mailmap file

### PR DESCRIPTION
**Pull request by cbm755**
This deduplicates contributors in the git log.

[skip ci]

### CODE REVIEW

**Comment by cbm755** [comment]
@genuinelucifer @trueutkarsh @maprieto please let me know if the email address *on the left* is incorrect or not preferred:
````
Abhinav Tripathi <genuinelucifer@gmail.com> <genuineabhinav@gmail.com>
Andrés Prieto <prieto.aneiros@gmail.com> maprieto <prieto.aneiros@gmail.com>
utkarsh <utkarshgautam247@gmail.com> utkarsh <iamutkash@cse.iitb.ac.in>
````

**Comment by genuinelucifer** [comment]
Alright by me. Any of the 2 are good. I would prefer `genuinelucifer@gmail.com` (the one on the left)! :+1:

**Comment by trueutkarsh** [comment]
left one is fine by me.

**Comment by cbm755** [comment]
2 out 3 ain't bad!  Merging.

@maprieto of course we can still change it later.

**Pull request merged**
