### PR TITLE
Integral transforms

### PR DESCRIPTION
**Pull request by maprieto**
This pull request includes patches for the (i)Laplace and (i)Fourier functions to handle Dirac deltas and Heaviside functions adequately and (i)Fourier transforms of simple functions such as constant ones, trigonometric functions (see the new tests included in each function). These patches solve partially issue #251

### CODE REVIEW

**Comment by cbm755** [comment]
Why don't we try to get this or at least parts of it into SymPy?  I really like the idea of staying slim and fixing SymPy instead...

**Comment by cbm755** [comment]
I think we need this, its just a think SymPy needs this too!

**Comment by maprieto** [comment]
I agree with you: it would be great to keep the symbolic package as slim as possible. However, since the new patches provide some basic functionality on these functions, it's worth it to include them (at least until sympy has solved them). Feel free to share these patches with those collaborators involved in the sympy development.

**Comment by cbm755** [comment]
Well, I feel it will be a lot of work for me:
1. need to understand these changes
2. need to sort out where to try to patch this into SymPy.
You've already done 1 so are much ahead of me.  Can you help with 2?

There was a recent discussion on the SymPy maillist that touched on this:
https://groups.google.com/forum/#!topic/sympy/2FVQRtZFpeY

**Comment by maprieto** [comment]
Ok! I'll post the possibility of use this patch on SymPy on the discussion that you've referred

**Comment by cbm755** [comment]
I'll bite the bullet and merge this.   I have not carefully vetted this code.  I would still like to see these improvements go upstream.

**Comment by maprieto** [comment]
I agree with you: I'd like to see a new smart implementation of this kind of improvements upstream in Sympy. Meanwhile, it can be considered as a partial remedy.

**Pull request merged**
