### PR TITLE
Update (i)fourier and (i)laplace functions

### PR DESCRIPTION
**Pull request by maprieto**
The workaround for issue #183 is mainly based on the computation of the general solution of the homogeneous system and a particular solution of the ODE system by using Laplace transforms. It only works on sympy 0.7.6 since Laplace transforms are applied to matrices (which is not supported on 0.7.5). As a previous step, the ODE system is written in matrix form.

Some additional features have been added to dsolve for ODE systems:
* Constant parameters can be used in the initial conditions (both in unknown arguments and their values)
* It's possible to describe the initial conditions by means of a linear system of equations with unknowns x(0), y(0),...

Obviously, there are some drawbacks for an implementation based on Laplace transforms:
* Its performance depends basically on the computational cost of the Laplace transform, which is pretty poor in some cases
* The solution is not explicitly computed in those linear systems with a rhs without an explicit Laplace transform or when the eigenvalues of the system matrix are not simple enough.

### CODE REVIEW

**Comment by cbm755** [comment]
Have you looked at upstream to see what the problem is?  (I haven't)

I prefer to fix it there (keeping octsympy as *thin* as possible).  If we don't know why this simple thing fails, its a bit worrying to rely on that code in other situations.  In general, I don't want to play wack-a-mole against sympy's bugs, while our dsolve and theirs diverge further and further.

Does this workaround happen *only* when there is a non-constant forcing?  That might be ok temporarily (similar to the ICs thing).  If we have this sort of workaround, it should be as narrowly defined as possible (apologies for not reading your code in enough detail to answer this myself).

I'm not likely to think about this for a week or so :(

**Comment by maprieto** [comment]
I've looked for these issues related to dsolve appled to ODE systems and I couldn't identify the source of the wrong solutions (maybe related to the classification of systems, identifycation of right-hand sides...?). Anyway, I'm totally agree with you to keep the code as thin as possible, but pushed for being able to handle ODE systems in my courses, I've decided to implement a workaround for dsolve. Currently, dsolve use the Laplace transform approach for any kind of ODE system (independently of the type of the forcing terms) and keep the sympy function dsolve for scalar ODEs.

Feel free to merge it temporaly at the master branch. Anyway, I'll use it for my courses while the bug in sympy is not fixed.

**Comment by cbm755** [comment]
That's fine: I assume you have it place for your course, whether I not I merge this?

**Comment by maprieto** [comment]
Right, don't worry!...and, for the following months (from february to june) an undergraduate student (in computer science) will be involved working with octsympy (firstly, studying the implementation and then trying to fix some issues, implementing new functions,...). So, from time to time, we'll propose you a merge with some contributions.

**Comment by cbm755** [comment]
> Right, don't worry!...and, for the following months (from february to
> june) an undergraduate student (in computer science) will be involved
> working with octsympy (firstly, studying the implementation and then
> trying to fix some issues, implementing new functions,...). So, from
> time to time, we'll propose you a merge with some contributions.

Right-on!  Look forward to it.

**Comment by cbm755** [comment]
@maprieto I completely missed this, as I just assumed it was the same PR as before.  But this is different and I'll take a look.

(You should probably use branches for each PR)

**Comment by maprieto** [comment]
My apologies: It was my fault. For the next PR, we'll try to identify the target of the pull request using independent branches.

**Comment by cbm755** [comment]
no problem!  Merged these fourier commits in #246, so closing this.

**Pull request closed without merging**
