### PR TITLE
change @sym/dot to match the behavior of @double/dot (fix #426)

### LINKED ISSUE #426: octsympy `dot` function disagrees with octave core `dot` function
Hi,

First, my octave version:
```
GNU Octave, version 4.0.1
Copyright (C) 2016 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.

Octave was configured for "x86_64-pc-linux-gnu".

Additional information about Octave is available at http://www.octave.org.

Please contribute if you find this software useful.
For more information, visit http://www.octave.org/get-involved.html

Read http://www.octave.org/bugs.html to learn how to submit bug reports.
```

My octsympy version:
```
OctSymPy v2.2.4: this is free software without warranty, see source.
Initializing communication with SymPy using a popen2() pipe.
Some output from the Python subprocess (pid 4926) might appear next.
Python 2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160409] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```

Consider the following:
```
octave:3> dot([1 i], [i 2])
ans =  0 - 1i
```
```
octave:4> dot(sym([1 i]), sym([i 2]))
ans = (sym) 3⋅ⅈ
```
The octave core `dot` function is computing complex inner product (conjugate linear in 1st slot),
while the octsympy `dot` function is computing real inner product (bilinear).
Is this a bug?

### PR DESCRIPTION
**Pull request by alexvong1995**
This fix #426.

### CODE REVIEW

**Comment by alexvong1995** [comment]
Some tests fail, I will try to fix them and re-submit a PR.

**Comment by cbm755** [comment]
Thanks!

I haven't looked at the failures, but I'll bet some tests need to have `syms x real`.

**Comment by cbm755** [comment]
Hi @alexvong1995 I looked at the test failures: its the [doctests](http://octave.sourceforge.net/doctest/) for `@sym/dot`: i.e., the documentation needs fixed.

Let me know if you'd prefer that I do this.

**Comment by alexvong1995** [comment]
Hi, I move the commits into a new branch, so I close this now.
I also fix the documentation in the new branch, so it should work now.

**Pull request closed without merging**
