### PR TITLE
add isassumption

### PR DESCRIPTION
**Pull request by latot**
You know.

Fixes https://github.com/cbm755/octsympy/issues/548

### CODE REVIEW

**Comment by cbm755** [comment]
See https://github.com/cbm755/octsympy/issues/548#issuecomment-247174684

**Comment by cbm755** [comment]
I like what @mtmiller said would be better: just make it return true or false: more generally useful than raising an error.

**Comment by mtmiller** [comment]
I also think it would be more useful to behave more like `isa` or `ishandle`, take a single argument that is an array, and return an array of `logical` of the same size. The caller can then use `any` or `all` if they want to interpret the results either way.

**Comment by cbm755** [comment]
... and @latot's script would start with
````
assert (all (isassumption ({'real', 'finite'})), "unsupported assumptions, upgrade your SymPy?")
````

**Comment by mtmiller** [comment]
Yes that looks better to me.

Incidentally what versions of Sympy are we talking about here?

**Comment by cbm755** [comment]
IIRC, `0.7.5` used `bounded` instead of `finite`.  I dropped support for 0.7.5.
No idea after that.

@mtmiller: This is all happening because we (octsympy) used to have a whitelist of allowable assumptions.  @latot changed it to that whatever assumptions SymPy has are exposed.

**Comment by mtmiller** [comment]
Thanks, I saw that change, just wasn't sure which versions of Sympy are actually affected, e.g. missing `prime` or `rational` assumption labels, etc.

**Comment by mtmiller** [comment]
Grepping the sympy history, it looks like 0.7.6 has the same list of assumptions that 1.0 has. Yes, 0.7.6 added `algebraic`, `rational`, `transcendental`, `infinite`, and `nonzero` over 0.7.5.

Just curious what are the practical cases being addressed here. Earlier comments suggested that `real` or `prime` or `polar` may or may not be supported in a particular version of Sympy, but that actually seems to not be possible.

**Comment by cbm755** [comment]
I'm not aware of a practical use case.

(There has been a change in octsympy in that `syms q prime` used to make two variables, now it makes a `q` which is assumed prime.  But adding `isassumption` doesn't help with that.)

**Comment by latot** [comment]
Hi, mm, when i do assumeCheck i think basically in this things:
   * If the user use an assumption it can't be replaced, that mean in general the user can't do something to cover it if don't is supported, and if can do something the most probable is will need rewrite part of the script, so the best its get an error i think.
   * If don't exist an assumption the user shouldn't start searching in all are using which isn't supported, for that reason this function check one by one. 

So, with this in consideration, what are yours expectations for this functions as users and develop?

**Comment by mtmiller** [comment]
I understand what you want to accomplish. You want a very easy `assert`-like syntax where you can do something like

    assert_assumptions real positive prime foo bar
    syms x y z real positive prime foo bar

with a hardcoded error message listing the assumptions that are not supported. If you both agree this is something useful for the user, don't let me stop you.

IMHO having a function check a cell array of assumptions is much more flexible and useful, to have either _instead_ or _in addition_ to what you want.

I would rather use something like this

    names = {"real", "positive", "prime", "foo", "bar"};
    idx = isassumption (names);
    if (any (names(idx))
      error ("myfunc: these assumptions are not supported: %s", strjoin (names(!idx), ", "));
    endif

This gives me the flexibility to error if I want to, with my own error message format, or to try to continue without certain assumptions if possible.

If you want to have both options available, then your check/assert function could be written like what I've shown here.

To me, the ambiguous `syms` command syntax is best suited for REPL interactive work anyway.

**Comment by latot** [comment]
Okidokis, thx for your comment, when i have a little time i'll write it.

**Comment by cbm755** [comment]
>  If you both agree this is something useful for the user, don't let me stop you.

FTR, I *do not* think it is useful.

**Comment by latot** [comment]
Okidokis, what do you think?

**Comment by latot** [comment]
Code ready and formatted.

**Comment by cbm755** [comment]
There are variously places in the code where we check if a string is an assumption.  I think at least in `syms` and possible in `@sym/sym`: basically everywhere where `assumptions('possible')` is called.  Could any of that code be simplified to instead use the new `isassumption`?  If it cleans up that existing code, its probably worth merging (even if I don't have a use for this myself).

**Comment by latot** [comment]
mm, you are right, i fix that concept in this pr: https://github.com/cbm755/octsympy/pull/594
i think i can update it or mix with the classdeff.

**Comment by cbm755** [comment]
I think a separate PR that builds on top of this would be good.  #594 is too big!

**Comment by latot** [comment]
yes, but sadly i try split it, but test fails to much, i fix a concept and something send an error, then i fix it and again other, for that reason is too big.... D:

**Comment by cbm755** [comment]
Its ok, we can chip away at it, `@sym/sym` is a mess so probably good ideas in there.  But let's tackle the `isassumption` thing first, separately.  So leave this PR, and make another one that builds on it to use `isassumption` internally.

**Comment by cbm755** [comment]
Maybe unclear: I mean the *current* `@sym/sym` is a mess, so probably good ideas in your PR to clean it up.

**Comment by latot** [comment]
aa, right, one of the ideas of that pr is do that!

**Comment by cbm755** [comment]
Possible to merge this before #594?  Just need to use the `isassumption` stuff as mentioned above in https://github.com/cbm755/octsympy/pull/551#issuecomment-251535399

**Comment by latot** [comment]
Hi, yes, i'll need update this function, because sym function need a better checker, i'll notice when this is ready.

**Comment by latot** [comment]
Hi, after read and think this, i conclude with the actual behaviors we can't use this function for the sym function, for one reason, we don't have a way to can index structs, sym support cells/chars and structs, assume, assumeAlso uses structs to get and set assumptions.
So, for now i can see 2 ways, first use two functions to check assumptions, one for user, and other for sym function to can keep the actual functionalities, the other way, remove struct support from sym function and rewrite the functions to use cells/char to set and get the assumptions.

Thx. Cya.

**Comment by cbm755** [comment]
Note: now there is an "private/check_assumptions" in master.

**Comment by cbm755** [comment]
not sure if there is anything here left to merge, closing.  Of course reopen if you still wanted to work on this.

**Pull request closed without merging**
