### PR TITLE
Deprecate Octave 3.8

### LINKED ISSUE #271: deprecate Octave 3.8 support
Perhaps after next Ubuntu LTS is ok?  16.04?  

or maybe sooner, I'm not running tests on 3.8 any more...

There is still some 3.6 cruft around too, clean that up as well.

### PR DESCRIPTION
**Pull request by cbm755**
Fixes #271.

I probably won't merge this until the next ubuntu LTS is out: lots of people are still on Octave 3.8 because of 14.04 LTS.

Also, we can currently run CI tests again for 3.8 so not too much bit-rot (I hope avoiding regressions like #268).

TODO list:
- [x] Add minimum octave version to DESCRIPTION file.

### CODE REVIEW

**Comment by mtmiller** [comment]
Does Travis support Ubuntu 16.04 yet? That's probably the primary reason not to drop support for Octave 3.8 yet.

You already have a minimum version of SymPy that is newer than comes with Ubuntu 14.04, requiring users to install a new SymPy is easier, but not much different from asking them to install a new version of Octave (and I can provide the PPA to install 4.0.x on 14.04).

**Comment by cbm755** [comment]
thanks!  I already use someone's PPA for Travis to get Octave 4.  I'll probably go ahead with this.

**Comment by mtmiller** [comment]
I see, I should have looked at the config file first :wink: 

The `ppa:octave/stable` PPA is the one I maintain.

So yeah, you are already handling 14.04 fine with an updated Octave and SymPy, so I don't know that there's much need to hold on to Octave 3.8 support if it gets in the way.

**Comment by cbm755** [comment]
merged to `dev_v250` branch.

**Pull request closed without merging**
