### PR TITLE
private/python_ipc_native: Add new function 'dbout'.

### LINKED ISSUE #1210: pythonic: add `dbout` command
@alexvong1995 pointed out that dbout does not work on pythonic backend.

Possibly its just `print`?   Anyway, needs to be added to `python-header` or equivalent.

### PR DESCRIPTION
**Pull request by alexvong1995**
Fixes #1210.

* inst/private/python_ipc_native.m: Add it.
* inst/private/python_header.py: Adjust accordingly.

### CODE REVIEW

**Comment by alexvong1995** [comment]
If this looks good, I'll merge it to https://github.com/cbm755/octsympy/tree/Array_not_Matrix and the mat_rclist_* branch that I am working on.

**Comment by cbm755** [comment]
sure, looks good to me!

**Comment by cbm755** [comment]
Actually, you are correct: this should be merged to main.

**Comment by cbm755** [comment]
I'll merge it now and you can cherry-pick to any other branches you need.

**Pull request merged**
