### PR TITLE
Add assumption number to see which test fails...

### PR DESCRIPTION
**Pull request by genuinelucifer**
trying to build on travis to see the result

### CODE REVIEW

**Comment by cbm755** [comment]
My suspicion from yesterday's tests is that it fails the first time pycall takes an argument... just in case that helps.

**Comment by genuinelucifer** [comment]
I added some pycall tests.. But they seem to pass :(
Well, I'll try some more tests...

**Comment by genuinelucifer** [comment]
So, for sym pycall throws exception and then terminates. While for anything else except strings it is directly causing segfault!
Any suggestions? @mtmiller

**Comment by cbm755** [comment]
We're on Octave 4.0.2, with a non-master branch of PyTave... I suspect @mtmiller will tell us to try to octave unstable PPA.

Perhaps you can try to track down the exception bug in pyexec et al:
https://bitbucket.org/mtmiller/pytave/issues/24/pyexec-inconsistent-error-handling

**Comment by genuinelucifer** [comment]
ohk. I'll try that then. :)

**Comment by cbm755** [comment]
Also this one:
https://bitbucket.org/mtmiller/pytave/issues/16/octave-to-pythoncc-gives-cryptic-error-msg

**Comment by cbm755** [comment]
In fact isn't 16 likely what we see on travis?  Anyway, the point is there are many PyTave bugs that make this harder to debug: let's spend some time fixing PyTave.

**Comment by genuinelucifer** [comment]
Sure. I guess most of the work on `pytave_ex` is done anyway. We can definitely now focus on PyTave bugs..

**Comment by cbm755** [comment]
Yes, or at least this first draft of `pytave_ex` is done :)

**Comment by genuinelucifer** [comment]
I did some changes in pytave_ex. Trying to bring those here caused this wreck and this has conflicts. I will close this PR, test travis on the pytave_ex branch directly and when travis starts working I'll squash the travis commits on pytave_ex...

**Pull request closed without merging**
