### PR TITLE
sym constructor: add deprecation warning for sym(cell)

### PR DESCRIPTION
**Pull request by cbm755**
Basically this PR is to top using `varargin = sym(varargin)` and make calls to `sym(cell)` give a warning.

### CODE REVIEW

**Comment by cbm755** [comment]
@genuinelucifer and @latot please review.

@latot I imagine you would prefer a helper function called something like `cell_to 
_cell_of_syms`.  I'd probably consider a PR that does that, but for now, here is my solution.

**Comment by genuinelucifer** [comment]
:+1:  
Looks good to me. Will be quite handy to finally get rid of `symarray`.

**Comment by cbm755** [comment]
ok,merging.

**Comment by latot** [comment]
mm, related with this, maybe improve num2cell to can do ```num2cell(sym(varargin))```?

if i remember right in SMT cells are transformed to arrays.

Thx. Cya.

**Comment by cbm755** [comment]
In fact, core Octave's num2cell seems to DTRT for sym arrays!  A pleasant surprise.  I will add a test for it.

Thanks for this.

**Pull request merged**
