### PR TITLE
[WIP] fix adjoint

### PR DESCRIPTION
**Pull request by latot**
maybe if you like split this to adjoint and adjointc, but actually we don't have exactly funcs with that behaviors, and ajoint its technically part of SMT, and ajoint with conjugate part of SymPy, so i think make sense have both in the same place.

Fixes https://github.com/cbm755/octsympy/issues/535

### CODE REVIEW

**Comment by latot** [comment]
first test of travis works, the second fails because travis is loose.

**Comment by latot** [comment]
Okidokis, Fixed, a little question what means WIP? (i'm imagining "work in progress")

**Comment by cbm755** [comment]
yes, that's right.  Helpful to mark PRs that are not ready for merging.

**Comment by cbm755** [comment]
This still doesn't look like the right thing to me, see my comment https://github.com/cbm755/octsympy/issues/535#issuecomment-244856762

**Comment by latot** [comment]
ups, you are right, i was confused because exist an equal name of adjoint in sympy and SMT, but are differents, now is right and match with the doc of SMT.

**Pull request merged**
