### PR TITLE
Release v3.0.1

### PR DESCRIPTION
**Pull request by alexvong1995**
Checklist
---------

  * [X] Update sympref.m:

      - [X] update version number (remove "+", check if bump needed).

  * [X] Update DESCRIPTION file (version number and date).

  * [X] Update NEWS file (date, version number, reformat).

  * [X] Update INDEX file for any new functions.

  * [X] Check minimum sympy version is consistent: its in
    DESCRIPTION, assert_have_python_and_sympy.m

  * [ ] Packages: need to run the following two scripts:

      - [ ] Use the maintainer makefile: "make clean", "make dist".

      - DEPRECATED: make_windows_package.sh, use "day-to-day testing" mode.
        Run this script "out of tree", it will clone a clean copy.
        Make sure py2exe, mpmath, sympy are the most recent versions.

  * [ ] Test regenerating html documentation: "make html"

  * [ ] Run "make release" and record the md5 sums.

  * [ ] Test on Matlab if possible.

  * [ ] Test on Windows if possible.

  * [ ] Ensure sourceforge and github both have up-to-date main branch.

  * [ ] Create ticket for release on sourceforge.  Upload tarball, html
    tarball and md5sums.

      - [ ] get checklist https://wiki.octave.org/Reviewing_Octave_Forge_packages

      - [ ] fill it out as best we can

      - [ ] Ticket should include the git hash to be tagged.

  * [ ] tagging happens after review, by admins!

      - [ ] If packages seem ok, hopefully someone else will +1 the release but this
        is no longer essential (summer 2022)

      - [ ] then we can tag:

          `git tag -a v3.x.y -m "Version 3.x.y"`

      - [ ] Follow the admin instructions under the review wiki above:

          `sftp` is useful for looking, and can then use `rsync`, something like
          `rsync -auvn --delete ./tmp/symbolic-html/symbolic/ <user>@web.sourceforge.net:/home/project-web/octave/htdocs/packages/symbolic/`
          (only certain users can do this: ask cbm for now)
         
      - TODO: summer 2022: longer term, we might invert this process, tagging on github
        before review.

  * [ ] Make sure tags are current on both sourceforge and github.
    `git push --tags origin main`.
    `git push --tags sourceforge main`.
    (cbm can do this part, TODO and it may not be necessary long term)

  * [ ] Do github-related release tasks:

      - DEPRECATED: Redo the Windows bundle package (using tag mode, see script).

      - [ ] compute the md5sums, upload the packages to github release
        page, and copy-paste the md5sums.  These must match the
        sourceforge md5sums.  Also compute sha256sum.

      - [ ] Do github release (copy-paste from last time, update link).

  * [ ] Update the https://gnu-octave.github.io/packages/ yaml file

      - [ ] see https://github.com/gnu-octave/packages/blob/main/CONTRIBUTING.md

      - [ ] send pull request

AFTER release
=============

  * [ ] Bump version by appending "+" in sympref.m and DESCRIPTION.

  * Optionally, update the make_windows_bundle script.  DEPRECATED.

### CODE REVIEW

**Comment by alexvong1995** [comment]
I'll merge before the end of 2022-08-09 UTC if there're no problems

**Comment by cbm755** [comment]
Looks good, merge whenever

**Comment by alexvong1995** [comment]
I think I've done everything on the checklist except the sourceforge, octave packages and after release tasks.

**Comment by cbm755** [comment]
Ok.  The intended workflow was to post the binaries to sourceforge before tagging the release, but that's ok, I wasn't super happy with that (would make it hard to automate releases with CI in future).

- - - -

I think we should do the "ticket at SourceForge" part of of the workflow, at least for another release or two.

Here's the previous release: https://sourceforge.net/p/octave/package-releases/484/

I will then pull the tar from there and the html and post them.  You can read more about this release process on the wiki: https://wiki.octave.org/Reviewing_Octave_Forge_packages

**Comment by alexvong1995** [comment]
We discussed about this in more details. So basically, I thought we can do the github and sourceforge release in parallel. But actually, the intended workflow is to upload the generated tarball to sourceforge to get a review first and then move on to other tasks. I'll keep this in mind for future releases (until the sourceforge repo is retired). All good!

**Comment by alexvong1995** [comment]
See closed ticket in https://sourceforge.net/p/octave/package-releases/486/
See also *post-release bumps* #1204

**Pull request merged**
