### PR TITLE
configure script to detect Python and SymPy

### PR DESCRIPTION
**Pull request by cbm755**
Now that we are the symbolic package, users can install from within Octave using `pkg install -forge symbolic`.  I have not tested this when Python and/or SymPy are missing.

But it would be nice if it gives an error at install time, telling people to install Python and SymPy first...

I'm no expect on autoconf, etc, but this should be easy enough for someone who is!

### CODE REVIEW

**Comment by cbm755** [comment]
Eh!  Did not know you could migrate an issue to a PR!  neat.

I'm looking into this... do you know how to do a version check?  Need minimum version sympy 0.7.5.

**Comment by carandraug** [comment]
Done. It will now fail if version < 0.7.5

**Comment by yoihito** [comment]
Hey-hey! It fails on python 3.4.2. `configure.ac` has some exceptions when it tries to get SymPy version.

**Comment by cbm755** [comment]
Thanks @yoihito   Can you file a new bug with the text of the exceptions?  (If you're on Windows, perhaps its #236?)

**Comment by carandraug** [comment]
@yoihito I have no experience with Python 3 at all. What exception do you get? Does the package even supports python 3 at all? If not, a better check would be to croak for experimental python versions.

**Comment by cbm755** [comment]
thanks @carandraug but @yoihito has already fixed this in ca17768dcb40c9aef47a1fa2a8e759d2ffc115c1.

For the record, we do (recently) support Python 3.  It should run with either Python 2 or Python 3.

**Pull request merged**
