### PR TITLE
subsref: make output dims agree if input is vector

### LINKED ISSUE #735: non-deterministic test failures (again)
Deja vu, but I'm seeing non-deterministic test failures from `@sym/subsref`:

````
>>>>> processing @sym/subsref.m

***** test

 % 1D arrays, does right with despite warning

 r = [1:6];

 ar = sym(r);

 c = r';

 ac = sym(c);

 Ir = rand(size(r)) > 0.5;

 Ic = rand(size(c)) > 0.5;

 assert (isequal (ar(Ir), r(Ir)))

 assert (isequal (ac(Ic), c(Ic)))

 s = warning ('off', 'OctSymPy:subsref:index_matrix_not_same_shape');

 assert (isequal (ar(Ic), r(Ic)))

 assert (isequal (ac(Ir), c(Ir)))

 warning (s)

!!!!! test failed

assert (isequal (ac (Ir), c (Ir))) failed
````
Last time, this was caused by `rand` choosing some "corner case" (e.g., such as all true or all false).  Maybe @nvs-abhilash (or someone else) feels like playing detective to track this down to a simpler case?

### PR DESCRIPTION
**Pull request by mtmiller**
Something like this should fix #735.

Needs some tests added in subsref.m for the degenerate cases that are actually causing the random failures. Any improvements or suggestions to what I have so far?

### CODE REVIEW

**Comment by cbm755** [comment]
@genuinelucifer last changed that code so let's get his opinion.

Tests look good to me.

**Comment by genuinelucifer** [comment]
I haven't tested it but It looks good.  
  
I have just one question though, I used size of find which is actually what octve would return in such cases. Why isn't that enough? Sorry for not testing anything. You ca merge this, I'll test it in evening and post here if needed.

**Comment by cbm755** [comment]
@genuinelucifer no hurry, I'll wait until you've looked it over.

**Comment by mtmiller** [comment]
@genuinelucifer the size of find is correct in most cases.

    >> size (find (false (1, 10)))
    ans =
    
       1   0
    
    >> size (find (false (10, 1)))
    ans =
    
       0   1
    

That is correct and good enough when `A` is a two-dimensional matrix.

The problem that this change is fixing is when `A` happens to be a row or column vector, then the dimensions of it take precedence over the dimensions of the logical indexing array. The singleton-ness of `A` dictates what the shape of the empty output array should be.

    >> size ((ones (10, 1))(false (10, 1)))
    ans =
    
       0   1
    
    >> size ((ones (10, 1))(false (1, 10)))
    ans =
    
       0   1
    

Your change was correct and you didn't do anything wrong. The only thing missing was tests for the case when a vector is indexed by another logical vector, and the shapes either agree or don't agree.

**Comment by mtmiller** [comment]
@cbm755 I plan on squashing these commits, so don't merge until I remove WIP from the title.

**Comment by genuinelucifer** [comment]
> The problem that this change is fixing is when A happens to be a row or column vector, then the dimensions of it take precedence over the dimensions of the logical indexing array.

Thanks. I get it now. Looks great! :+1:

**Comment by mtmiller** [comment]
Rewritten and ready to merge, thanks all

**Pull request merged**
