### PR TITLE
Rename helper_op to elementwise_op

### PR DESCRIPTION
**Pull request by cbm755**
This is on top of #655.

@latot to review, but can wait until #655 goes in.

### CODE REVIEW

**Comment by cbm755** [comment]
I rebased this.  Ready for review.

**Comment by mtmiller** [comment]
Yay, name looks much better, I'll rebase #649 on this after it gets merged.

**Comment by latot** [comment]
Hi, i think is fine! Great

**Comment by cbm755** [comment]
Thanks both!  Will merge when tests pass.

**Comment by latot** [comment]
O_O

```
Your Octave version is 3.8.1 but Octsympy is currently untested on
anything before 4.0.0.
```
lot of times........................................................................................................

**Comment by mtmiller** [comment]
The build failed because of a temporary Ubuntu PPA update failure, need to kick it again.

**Pull request merged**
