### PR TITLE
Adding save and load functionality for sym objects

### PR DESCRIPTION
**Pull request by genuinelucifer**
Fixing #376 

- [x] Complete the functions and tests
- [x] Fix The doctests

### CODE REVIEW

**Comment by genuinelucifer** [comment]
@cbm755 Please review
.
Also, although I have worked with functions in octave but I was really shocked to see I am unable to define a function with 1 argument and then call it by passing an string as the argument. I always get the error that I mentioned. Any suggestions?

**Comment by cbm755** [comment]
I will take a look.  Re: string argument: I'm not sure what you mean.  But please note any method defined as `@sym/method.m` must have at least one `sym` argument: that is how Octave identifies it as a method for `sym` object.  You'll note Symbolic has some functions in `inst/`: this is why.

Does that help?

**Comment by cbm755** [comment]
Have you read http://www.gnu.org/software/octave/doc/v4.0.1/Manipulating-Classes.html?

I'm not sure saveobj is supposed to actually create a file: looks to me more like some preprocessing...  But I admit that I have not looked carefully at it.

Anyway, what we need to support is:
````
>> syms x
>> a = 42;
>> save myfile x a
>> clear
>> load myfile
>> x
  x = (sym) x
>> a
  a = 42
````

**Comment by genuinelucifer** [comment]
> any method defined as @sym/method.m must have at least one sym argument: that is how Octave identifies it as a method for sym object
Oh that's why I couldn't define it. Thanks.
.

> Have you read http://www.gnu.org/software/octave/doc/v4.0.1/Manipulating-Classes.html?
Sorry. I read the matlab documentation for the same. Now it is more clear. I will implement the functions and try again.

**Comment by genuinelucifer** [comment]
@cbm755 Please review
.
It works correctly now. And all the tests pass.
.
Also, I saw that there was no need to create these 2 files (except that these files provide some tests to check). The ```save myfile x``` and ```load myfile``` worked perfectly without doing anything...

**Comment by genuinelucifer** [comment]
Also, I have to rely on buildbot to check the doctests. (hence a few more pushes per PR).
I tried to install doctest but many errors arise.
I solved some of them but am stuck with one for now.
.
Whenever I run ```doctest @sym/somefile.m``` it always shows fail with the ```got``` part as:
```
got     : ??? 'doctest_evalc' undefined near line 140 column 29
```

**Comment by cbm755** [comment]
I suspect that means you did not install doctest correctly (that file needs to be compiled).

`pkg install -forge doctest` is the recommended way to install packages.

I had no idea save/load was already working! :)  I will review this...

**Comment by genuinelucifer** [comment]
I did install from forge only!
.
Well, here's how I did it:
- I ran ```sudo apt-get install doctest``` on linux terminal. After it got installed I remembered that it is not what I have to install. SO ,
- I ran ```pkg install -forge doctest``` in octave terminal. It showed many errors while installation and the installation did not complete.
- I ran doctest on linux terminal and found it complained about ```ghc``` and hence
- I ran ```sudo apt-get install ghc``` on linux terminal
- Then I went back to octave terminal and did ```pkg install -forge doctest``` and this time it installed perfectly!
- But now I am stuck with the error for ```got``` section!

**Comment by cbm755** [comment]
doctest and octave-doctest not the same thing!  ghc should be unrelated.  Probably you dev environment (gcc, etc) is/was incomplete.

Please report the errors you got with `pkg install -forge doctest` at https://github.com/catch22/octave-doctest

**Comment by cbm755** [comment]
> and this time it installed perfectly!

Seems unlikely (unless `ghc` just happened to have the same deps).  Can you `pkg uninstall doctest` and then try `pkg install -forge doctest`?

**Comment by genuinelucifer** [comment]
@cbm755 It's late night for me. I'll surely check the errors and report them to the doctest repo tomorrow. :)

**Comment by cbm755** [comment]
So, maybe we should not have saveobj/loadobj at all?  And put the tests somewhere else.  OTOH, if we every change the fieldnames then we'd need `loadobj` for backwards compatibility.  Not a review, just thinking out loud...

**Comment by cbm755** [comment]
One review item: the tests will need to delete `myfile` after use.  Also, should check if Octave has a function to request a temp file name form the OS.

We probably don't need many tests here, just one should be enough.

Another thought: we could save only the `.pickle` (in `saveobj`) and then re-create the other fields in `loadobj`.  Advantages/disadvantages...?

**Comment by genuinelucifer** [comment]
> So, maybe we should not have saveobj/loadobj at all? And put the tests
somewhere else.

Yes. That seems a better choice. Is there a common file for tests?

> OTOH, if we every change the fieldnames then we'd need loadobj for
backwards compatibility. Not a review, just thinking out loud...

Hmm :)

**Comment by genuinelucifer** [comment]
> One review item: the tests will need to delete myfile after use. Also,
should check if Octave has a function to request a temp file name form the
OS.

Hmm. Will check for such functionality.

> We probably don't need many tests here, just one should be enough.

Will do.

> Another thought: we could save only the .pickle (in saveobj) and then
re-create the other fields in loadobj. Advantages/disadvantages...?

Advantage probably to reduce the amount of data to be stored (will have to
do some tests to see how much)
Disadvantage mostly perfect(probably?!) recreation of the object?!

**Comment by cbm755** [comment]
> Is there a common file for tests?

Some stuff is in `misc.tst`.  Although I think at one point I was planning to move everything out of `misc.txt`

Another possibility is in `@sym/sym.m` (as the ctor is the main entry point of the class).

**Comment by cbm755** [comment]
`NEWS` should have an new bullet point too: `* saving/loading sym objects is now supported (it previously worked, by accident).`

**Comment by genuinelucifer** [comment]
@cbm755 I added the line in NEWS and also shifted the tests to ```@sym/sym.m```.
Now the tests use temp file names and also delete them after use.
Please review.
Should I squash the commits into one?

**Comment by cbm755** [comment]
I think you need `save(myfile, 'x')` or something like that.  I think currently it will save it to literally `myfile`?  But strange that `unlink` doesn't fail and then make the test fail!

Maybe we don't need a doctest.  Just a sentence in the docs something like you have already:
`It is also possible to save sym objects to file and then load them when needed in the usual way with the @code{save} and @code{load} commands`.

+1 for squashing.

**Comment by genuinelucifer** [comment]
> I think you need save(myfile, 'x') or something like that. I think
currently it will save it to literally myfile? But strange that unlink
doesn't fail and then make the test fail!

Strange indeed. I didn't thunk about that earlier. Will change it

> Maybe we don't need a doctest. Just a sentence in the docs something like
you have already:
> It is also possible to save sym objects to file and then load them when
needed in the usual way with the @code{save} and @code{load} commands.

Ohk will remove the doctest.

> +1 for squashing.

Will squash and push the changes in a couple of hours.

**Comment by cbm755** [comment]
`help unlink`: test should fail if ERR is nonzero.

**Comment by genuinelucifer** [comment]
@cbm755 Done.

**Comment by cbm755** [comment]
Great!  This is in.

FYI: I try to maintain matlab compatibility so I avoid using `"` for strings (e.g., in your test).

**Comment by genuinelucifer** [comment]
> Great! This is in.
>
> FYI: I try to maintain matlab compatibility so I avoid using " for
strings (e.g., in your test).
>

Oh. I'll try to remember that for future works.
Would you please point me to some other issue to work on?

**Pull request merged**
